test:
  mysql:
    host: 'mysql.sqlpub.com'
    port: 3306
    user: 'liruyi'
    password: '544dc8836263faa9'
    database: 'ruyi_testdb'
  redis:
    host: "redis-14102.c323.us-east-1-2.ec2.cloud.redislabs.com"
    port: 14102
    password: "SPD4KVOukJu7Zmn8saxlpxwMn4oeSfS5"